### ISSUE TITLE
Routing behaviour change since reitit-core-0.3.0-20190219.174913

### ISSUE THREAD

**Issue by kommen** [metosin/reitit#229]
```clojure
(def simple
    [["/" :root]
     ["/" {:name :create :method :post}]])

(r/match-by-path (r/router simple {:conflicts (constantly nil)}) "/")
```

In reitit-core-0.3.0-20190219.174913 this snippet matches the first route. In the latest snapshot version, the second route is matched instead.

**Comment by ikitommi** [comment]
# 🤦

Not good and I could reproduce it only with ClojureScript (`clojure-trie-compiler`). The root cause was that the linear router is now backed by a trie, which reorganizes linear lookup routes based on the path length. This is nice for non-conflicting routes, but TOTALLY INVALID with conflicting routes. Added a boolean whether to keep the original order or not -> `:linear-router` will always keep the order + a test to verify it works now. New `0.3.0-SNAPHSOT` deployed.

Sorry for bad code and thanks for reporting.

**Comment by kommen** [comment]
Thanks for the quick fix! I'll give the new snapshot a try tomorrow.
