### ISSUE TITLE
Use of undeclared Var reitit.impl/walk-one`

### ISSUE THREAD

**Issue by rafamedina** [metosin/reitit#278]
I have an error
I think I'm missing a dep but I'm sure which one

Any idea?
Thanks

Dependencies:
>   :dependencies [[org.clojure/clojure "1.9.0"]
                 [org.clojure/clojurescript "1.10.339"]
                 [reagent "0.8.1"]
                 [metosin/reitit "0.3.4"]
                 [metosin/reitit-schema "0.3.4"]
                 [metosin/reitit-frontend "0.3.4"]]

Error:
`Compile Warning file:/C:/Users/Sp/.m2/repository/metosin/reitit-core/0.3.4/reitit-core-0.3.4.jar!/reitit/impl.cljc
Use of undeclared Var reitit.impl/walk-one`

**Comment by miikka** [comment]
`metosin/reitit` should depend on all the reitit sub-packages, so I don't think you're missing a dependency. (If you depend on `metosin/reitit`, you do not need to add dependencies for `metosin/reitit-schema` and `metosin/reitit-frontend` separately, although there's no harm in doing so.)

`walk-one` is defined inside of a letfn where it is used in mutually recursive fashion. This should be correct, but I wonder if the ClojureScript compiler (or maybe Google Closure compiler) emits a warning anyway.

I'm not able to reproduce this. Since it's only a compiler warning, not an error, your code should compile. Have you tried if it works despite the warning?

**Comment by rafamedina** [comment]
You are right, it worked correctly
Thanks
