### ISSUE TITLE
Don't include full spec error in exception message when coercion response fails

### ISSUE THREAD

**Issue by danielcompton** [metosin/reitit#344]
https://github.com/metosin/reitit/blob/a19849fe58d6e5234e691ba0ed2201c1a8712db8/modules/reitit-core/src/reitit/coercion.cljc#L59

When a response coercion fails, currently that results in a very long error message with the entire spec error.

I'm not quite sure what a better error message could be, but perhaps limiting it to just mentioning the `:name` of the endpoint where coercion failed? e.g.

```
Response coercion failed: :my.api.purchase/checkout
```

**Comment by wandersoncferreira** [comment]
I had the same issue when providing my API to other partners with more low-tech-experience, they complaint a lot and they had a good point. Most of them were .NET programmers and the spec error made no sense whatsoever.

I fix it by overriding the exception handler to the whole application and providing a friendly version and logging the complete spec error to my internal usage.

https://github.com/metosin/reitit/blob/master/doc/ring/exceptions.md

**Comment by ikitommi** [comment]
yes, you can configure what get's printed. Wilth malli-coercon, you can actually parametrize the coercion itself which keys are present. Another change is to report all the error locations (header, body, query...), instead of just the first one that fails, collected these into 1.0.0 bundle-issue: https://github.com/metosin/reitit/issues/264

**Comment by ikitommi** [comment]
closing this as there is a way already.
