### ISSUE TITLE
Using Reitit for chat pattern matching

### ISSUE THREAD

**Issue by theronic** [metosin/reitit#411]
I'd like to be able to use Reitit for space-separated commands like:

```
(r/router
  [["/command1 {arg1} {arg2}" ::cmd1]
   ["/command2 {arg1} {arg2} {arg3}" ::cmd2]])
```

However, it seems that arg1 or arg2 are ambiguous because they are not slash-separated.

What would it take to constrain the possible values of arg1 and arg2 and to specify segment separator to be space instead of `/`?

**Comment by miikka** [comment]
Arguably this is a bug and using space as the separator should just work. It is not working of because this check:

https://github.com/metosin/reitit/blob/3a6985eb713aae7c02b4f63e339ab4b1e73a8a74/modules/reitit-core/src/reitit/trie.cljc#L170

Instead of `str/blank?`, maybe that should be `empty?`. Not sure if changing that breaks something.

**Comment by miikka** [comment]
@ikitommi Do you remember why that check is for blank strings and not for empty strings? Changing it to empty does not break any tests but it would make space-separated routing work.

**Comment by ikitommi** [comment]
don't remember. looks legit to change to empty.
