### ISSUE TITLE
Malli response coercision seems to do nothing at all

### ISSUE THREAD

**Issue by itaysabato** [metosin/reitit#498]
Maybe I'm crazy, but after much debugging, I became convinced Malli response coercion doesn't do anything.

Evidence:
Looking at [this line](https://github.com/metosin/reitit/blob/master/modules/reitit-malli/src/reitit/coercion/malli.cljc#L51), if no `encoder` parameter is passed, the encoding simply returns the value - [see here](https://github.com/metosin/reitit/blob/master/modules/reitit-malli/src/reitit/coercion/malli.cljc#L72).

Now, looking at how response coercion is defined [here](https://github.com/metosin/reitit/blob/master/modules/reitit-malli/src/reitit/coercion/malli.cljc#L180-L183), it seems that the returned coercer uses another coercer as its `encoder` which, in turn, gets `nil` as its encoder - which means nothing is ever encoded.

This is also what seems to happen in practice. I can provide more details about my use case, but it seems like it doesn't really matter, given this code.

Thanks.

**Comment by ikitommi** [comment]
The code looks fishy, similified it, might have fixed the issue and added tests to verify.

Root cause: malli `:response` encoding didn't have named traansformers attached to be used in encoding. Added a `application/json` transformer for the case user requested JSON from reitit.

Does that look any good?

**Comment by itaysabato** [comment]
Looks great, thanks!
Looking forward to the release :)
