### ISSUE TITLE
Serving Resources with Reitit

### ISSUE THREAD

**Issue by theronic** [metosin/reitit#71]
Trying to swap out Compojure and Bidi for Reitit.

How should I go about serving resource paths or static file paths with Reitit? Compojure has `resources` which calls its resource-response and add-mime-type helpers.

Is there an equivalent in Reitit?

**Comment by ikitommi** [comment]
currently, you should use ring helper functions for this. We could add a (data-driven) helper for this as it's a common thing.

**Comment by ikitommi** [comment]
Hi. played with this. there are at least two ways to do this right:

## from a route tree

```clj
(ring/ring-handler
  (ring/router
    [["/ping" (constantly {:status 200, :body "pong"})]
     ["/files/*file" (ring/create-resource-handler)]])
  (ring/create-default-handler))
```

This is great if the static files are served from non-conflicting paths.

## outside of a route tree

```clj
(ring/ring-handler
  (ring/router
    ["/ping" (constantly {:status 200, :body "pong"})])
  (some-fn
    (ring/create-resource-handler {:path "/files"})
    (ring/create-default-handler)))
```

This is good if the static files are served from otherwise conflicting paths, e.g. "/*".

## details

the `create-resource-handler` takes optional options map with keys:

*  `:parameter` the named wildcard parameter, defaults to `:file`
* `:root` the root to serve resources, defaults to `"public"`
* `:last-modified?` optionally add last-modified to responses
* `:path` optional path prefix (if served outside of a route tree, defaults to "/"

have a spike on implementing this, only for Clojure (not ClojureScript). Supports NIO, so really fast with servers supporting that. With the perf-optimized Immutant, few samples:

```
;;
;; start repl with `lein perf repl`
;; perf measured with the following setup:
;;
;; Model Name:            MacBook Pro
;; Model Identifier:      MacBookPro113
;; Processor Name:        Intel Core i7
;; Processor Speed:       2,5 GHz
;; Number of Processors:  1
;; Total Number of Cores: 4
;; L2 Cache (per Core):   256 KB
;; L3 Cache:              6 MB
;; Memory:                16 GB
;;
```

### Small file (17 bytes)

```
wrk -t2 -c100 -d2s http://localhost:3000/files/hello.json

34055 requests/sec
4.64MB / sec
```

### large file (406kB)

```
wrk -t2 -c10 -d10s http://localhost:3000/files/image.jpg

2798 request/sec
1.08GB / sec
```

### single huge file (775Mb)
````
wget http://localhost:3000/files/LilaBali2.pptx
(315 MB/s)
```

**Comment by ikitommi** [comment]
PR waiting for this: https://github.com/metosin/reitit/pull/79

**Comment by ikitommi** [comment]
Tested the Small File case with `ring-defaults` with `site-defaults`.

```
Requests/sec:   3524.16
Transfer/sec:    385.45KB
```

**Comment by azizzaeny** [comment]
hi, i struggle enough this day to implement middleware on `/` on `ring/reitit`...  to function {:middleware []]}
glad, this push rely help me alot... :+1:

**Comment by ikitommi** [comment]
in latest SNAPSHOT, `reitit.ring/create-resource-handler` supports new `:index-files` option. it defaults to `["index.html"]`: first a exact resource is looked, then all the index-files.

**Comment by ikitommi** [comment]
https://metosin.github.io/reitit/ring/static.html
