### ISSUE TITLE
Ring handler response coercion

### ISSUE THREAD

**Issue by ikitommi** [metosin/reitit#98]
With most Clojure ring-web libs, one can return anything from a handler and it get's coerced into a valid Ring Response:

* Compojure: https://github.com/weavejester/compojure/blob/master/src/compojure/response.clj
* Duct: https://github.com/duct-framework/module.web/blob/master/src/duct/handler/static.clj#L16

Reitit-ring should support something like this too, as otherwise, one has to always return a valid ring response map from handlers.

# Suggestion

* have a protocol `IntoResponse` and a middleware in `reitit.ring` to do this

Options how to integrate:

# Easy

*  by default, prepend that into all middleware chains by the `ring-router`
*  configurable via `ring-router` options `::ring/wrap-handler`?

# Simple

* user must prepend the default middleware into al chains (via `::middleware/transform` option)
* better control of what is happening?

**Comment by miikka** [comment]
Note that in case of Duct, you can't just return anything from the handler! You still need to return a valid-ish Ring response, it just has some extra smarts for doing the right thing when your `:body` is something more structured than a string or a stream.

I prefer the Duct way because I find "handlers should always return a response" easy to understand. When you can return just about anything, it makes it a bit too magical for my taste.

**Comment by ikitommi** [comment]
ok, not doing anything for this now.
